"""
Standard reject codes used across the Silver layer.

These constants ensure that all rejected records use
consistent, machine-readable reason codes.
"""

# Generic Validation Errors

INVALID_STATUS = "INVALID_STATUS"

INVALID_TYPE = "INVALID_TYPE"

INVALID_VALUE = "INVALID_VALUE"

INVALID_DATE = "INVALID_DATE"

INVALID_RANGE = "INVALID_RANGE"

INVALID_QUANTITY = "INVALID_QUANTITY"

INVALID_PRICE = "INVALID_PRICE"

# Referential Integrity Errors

SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND"

MATERIAL_NOT_FOUND = "MATERIAL_NOT_FOUND"

PURCHASE_ORDER_NOT_FOUND = "PURCHASE_ORDER_NOT_FOUND"

PURCHASE_ORDER_LINE_NOT_FOUND = "PURCHASE_ORDER_LINE_NOT_FOUND"

GOODS_RECEIPT_NOT_FOUND = "GOODS_RECEIPT_NOT_FOUND"

WAREHOUSE_NOT_FOUND = "WAREHOUSE_NOT_FOUND"

# Business Rule Errors

INVALID_SUPPLIER_STATUS = "INVALID_SUPPLIER_STATUS"

INVALID_SUPPLIER_TYPE = "INVALID_SUPPLIER_TYPE"

INVALID_PAYMENT_TERM = "INVALID_PAYMENT_TERM"

INVALID_CURRENCY = "INVALID_CURRENCY"

INVALID_MATERIAL_CATEGORY = "INVALID_MATERIAL_CATEGORY"

INVALID_UNIT_OF_MEASURE = "INVALID_UNIT_OF_MEASURE"

INVALID_RECEIPT_DATE = "INVALID_RECEIPT_DATE"

INVALID_DELIVERY_DATE = "INVALID_DELIVERY_DATE"
